#      
#      $Id: Makefile.conf,v 1.43.2.4 2002/08/30 07:21:48 cgray Exp $
#	Copyright (C) 1999 Distributed Systems (DiSy) Group, UNSW, Australia.
#
#      This file is part of the Mungi operating system distribution.
#
#      This program is free software; you can redistribute it and/or
#      modify it under the terms of the GNU General Public License
#      as published by the Free Software Foundation; either version 2
#      of the License, or (at your option) any later version.
#      
#      This program is distributed in the hope that it will be useful,
#      but WITHOUT ANY WARRANTY; without even the implied warranty of
#      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#      GNU General Public License for more details.
#      
#      You should have received a copy of the GNU General Public License
#      along with this program; if not, write to the Free Software
#      Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


# MUNGI_ARCH. The architecture you wish to compile mungi for.
# This should be the only thing you need to change. Hopefully.
MUNGI_ARCH := alpha
# MUNGI_ARCH := mips

# DISY_HOME. Root of all tools.
DISY_HOME := /home/disy

# L4ROOT
# Where the l4 libraries and include files are
# This direcory should contain at least (and prob. more)
# You should just have to point it at where you have the l4
# distribution
#
# $(L4ROOT)/tools/dit/dit
# $(L4ROOT)/include/<machine includes>
# $(L4ROOT)/include/l4/<l4includes>
# $(L4ROOT)/lib/libl4.a
L4ROOT := $(DISY_HOME)/$(MUNGI_ARCH)L4/

# MUNGIROOT
# The root directory of the Mungi hierarchy
MUNGIROOT := $(shell pwd)

# Whether to build the test code (comment out to run the shell etc.)
# A 'make clean' will be needed to fix some kernel functions
# TESTING := 1

# generic compiler flags
WARN = -Wall -Wcast-align -Wstrict-prototypes -Wmissing-prototypes \
	-Wnested-externs -Wmissing-declarations -Wredundant-decls -Wshadow \
        -Werror
OPT := -O2 -pipe -fomit-frame-pointer
FREE := -nostdinc -ffreestanding
OTHER := -D_DEBUG_ -D_VERBOSE_ -DNULL=0 -DMUNGI -DCLOCK

# Define the TESTING flag if we are building the tests
ifdef TESTING
OTHER += -DTESTING
endif

# There is a bug with the Multia (21064) port of L4 - uncomment this
# if you are using this - it degrades performance, but prevents random
# register trashing
#HACK := -ffixed-8 -ffixed-9 -ffixed-10 -ffixed-11 -ffixed-12 \
#	-ffixed-14 -ffixed-15 -ffixed-25

CFLAGS := $(OPT) $(FREE) $(WARN) $(OTHER) $(HACK)

# where to find all the various includes/libs
INCLUDES := -I$(MUNGIROOT)/include -I$(MUNGIROOT)/kernel/include \
	    -I$(MUNGIROOT)/lib/mungi/asm/$(MUNGI_ARCH) \
            -I$(MUNGIROOT)/kernel/include/asm \
	    -I$(MUNGIROOT) -I$(MUNGIROOT)/drivers \
	    -I$(MUNGIROOT)/lib/libc/std_include \
	    -I$(MUNGIROOT)/lib/libc/include  \
            -I$(MUNGIROOT)/kernel/include/mungi \
            -I$(MUNGIROOT)/lib/libc/time \
            -I$(MUNGIROOT)/lib/libc/posix         \
            -I$(MUNGIROOT)/lib/naming/            \
	    -I$(L4ROOT)/include 

LDDIRS := 
LDLIBS = -ll4
LDFLAGS =

# Assembler flags
ASFLAGS := 

# Where to copy the new kernel to when you have finished
kerneldest = /tftpboot
kerneldest = friesian:/tftpboot/mungi.$(USER)
RCP = scp -p
RSH = ssh

CRT0 := kernel/src/asm/$(MUNGI_ARCH)/crt0.o
CRTS := lib/mungi/asm/$(MUNGI_ARCH)/crt0.o


################################################################################
#            Architecture options
################################################################################
KTARGET := $(MUNGI_ARCH)
ifeq (${MUNGI_ARCH}, mips)
##############
# MIPS machine
##############

XCCPREFIX = mips-sgi-irix6-
XCCPATH := $(DISY_HOME)/$(MUNGI_ARCH)crossdev/$(ARCH)/bin/

# RIPC compiles for restricted ipc. ie restricted printing
#RIPC=1
ifdef RIPC
CFLAGS += -DRIPC
endif

# Set MACHINE_TYPE to be one of the following:
# 
# DIZZY  will compile the indy timer binaries
# PROTB will compile for the Protoype board the kev and dave made
# ALG will compile for the algorithmics board
MACHINE_TYPE=PROTB
MIPSENV=1


# The const='' is because the Mips string.h forgets the const headers
CFLAGS += -D${MACHINE_TYPE} -Dconst=

CFLAGS	+= $(CFLAGS) -mips3 -mabi=64 -DMIPSENV -G 0 -mno-abicalls \
	  -DGCC -Wa,-non_shared,-G,0 
ASFLAGS	:= $(CFLAGS) 

INCLUDES += -I${L4ROOT}/include/kernel -I$(MUNGIROOT)/drivers/mips 
#LDLIBS =
LDDIRS += -L$(MUNGIROOT)/lib -L$(MUNGIROOT)/kernel/lib -L$(L4ROOT)/lib -ll4 
LDFLAGS +=

# Dit, not dite is used on mips - they should be merged at some point
# though
DITEFLAGS = -n -a
DITEOUT = $(TARGET).tmp
DITERESOURCEFLAGS = -a
DITE = $(XCCPATH)/dit

L4KERNEL := $(DISY_HOME)/$(MUNGI_ARCH)L4/kernel/kernel-serial
L4KERNEL := /home/cgray/work/mipsL4/src/kernel/kernel

else # ! mips
ifeq (${MUNGI_ARCH}, alpha)
##############
# ALPHA machine. Beefcake.
##############

L4ROOT := $(shell pwd)/../L4Alpha/
XCCPREFIX := alpha-linux-
XCCPATH := /home/brettn/crossdev/bin/

L4KERNEL :=  $(L4ROOT)bootpfile


INCLUDES := $(INCLUDES) -I$(L4ROOT)/include/lib -I$(L4ROOT)/include \
				-I$(L4ROOT)/include/lib/l4 \
				-I$(L4ROOT)/lib/klibc/asm/alpha/
 
LDDIRS += -L$(MUNGIROOT)/kernel/lib/klibc  -L$(L4ROOT)/lib
LDFLAGS += -N -nostartfiles -nostdlib
CONSOLE = drivers/console.o
CFLAGS	:= $(CFLAGS) -fno-strength-reduce -mno-fp-regs \
	  -freg-struct-return -DALPHAENV

ALPHABOOTLOADER := ../L4Alpha-bl/l4bl.nh 
ASFLAGS := $(ASFLAGS) -DALPHAENV

DITEFLAGS = $(TARGET).tmp
DITEOUT =  -o $(TARGET).dite ; mv $(TARGET).dite $(TARGET).tmp
DITERESOURCEFLAGS = $(TARGET).tmp -xr
DITE := dite
# ALPHA specific tools

ALPHAENV=1
endif # end ALPHA machine
endif # end MIPS machine



# location of the tools
CC	:= $(XCCPATH)$(XCCPREFIX)gcc
AS	:= $(XCCPATH)$(XCCPREFIX)gcc
LD	:= $(XCCPATH)$(XCCPREFIX)ld
AR	:= $(XCCPATH)$(XCCPREFIX)ar
DIT	:= $(HOME)/bin/dite
SIZE	:= $(XCCPATH)$(XCCPREFIX)size
STRIP	:= $(XCCPATH)$(XCCPREFIX)strip
NM	:= $(XCCPATH)$(XCCPREFIX)nm
CP	:= cp
MV	:= mv
TAGS	= ctags -R --sort=yes

# a special set of obj file for upcall to beable to use UserPrint 
UPCALL_USERPRINT_OBJ	:= lib/libc/stdio/vsprintf.o  	lib/libc/stdio/atob.o \
	 	lib/libc/stdio/str_fmt.o   	lib/libc/stdio/strichr.o \
		lib/libc/stdio/isdigit.o \
		lib/mungi/libmungi.a  \
                lib/libc/string/strncpy.o 	lib/libc/string/strlen.o \
		lib/libc/string/strcpy.o     lib/libc/string/strchr.o  \
		lib/libc/string/strcat.o

